export const pair=(fr,en)=>({fr,en});
export const business={name:pair("Bertrand","Bertrand"),phone:'+33605597685',whatsapp:'https://wa.me/33605597685',address:pair("France · adresse et zone d’intervention à confirmer","France · address and service area to be confirmed")};
export const photos={hero:'assets/collection-hero.webp',sofa:'assets/collection-sofa.webp',office:'assets/collection-office.webp',glass:'assets/collection-glass.webp'};
export const services=[
{id:'home',icon:'home',title:pair("Nettoyage des maisons et appartements","Home & apartment cleaning"),description:pair("Un soin complet des appartements meublés, maisons et villas, des pièces de vie aux cuisines.","Complete care for furnished apartments, homes and villas, from rooms to kitchens."),image:photos.hero},
{id:'sofa',icon:'sofa',title:pair("Nettoyage des canapés et tapis","Sofa & carpet cleaning"),description:pair("Rafraîchissez canapés, tapis et textiles pour un espace plus confortable.","Refresh sofas, carpets and upholstery for a more comfortable space."),image:photos.sofa},
{id:'construction',icon:'building',title:pair("Nettoyage après travaux","Post-construction cleaning"),description:pair("Éliminez les traces des travaux et des finitions pour un nouveau départ.","Clear away the traces of building and finishing work for a fresh start."),image:photos.hero},
{id:'glass',icon:'window',title:pair("Nettoyage des vitres","Window & glass cleaning"),description:pair("Un soin des vitres et fenêtres pour une vue dégagée et une finition éclatante.","Care for windows and glass for a clear view and a polished finish."),image:photos.glass},
{id:'deep',icon:'shield',title:pair("Nettoyage en profondeur","Deep cleaning"),description:pair("Une attention particulière aux cuisines, recoins et espaces nécessitant un nettoyage approfondi.","Extra attention for kitchens, corners and areas that need a deeper clean."),image:photos.hero},
{id:'office',icon:'building',title:pair("Nettoyage des bureaux et entreprises","Office & business cleaning"),description:pair("Des espaces professionnels propres et accueillants, avec un service adapté à votre activité.","Clean, welcoming workplaces with a service tailored to your business."),image:photos.office}
];
export const offers=[{id:'carpets',title:pair("Quatre tapis. Le cinquième est offert.","Four carpets. The fifth is on us."),description:pair("Disponibilité à confirmer auprès de Bertrand avant réservation.","Confirm availability with Bertrand before booking."),terms:pair("Le nettoyage du cinquième tapis est offert pour quatre tapis nettoyés. Dimensions et conditions d’éligibilité à confirmer.","Fifth carpet cleaned free when cleaning four carpets. Size restrictions and eligibility need confirmation."),start:'',end:'',status:'pending'},
{id:'new-home',title:pair("Nouveau logement, nouveau départ","New home, fresh start"),description:pair("Des formules de nettoyage après travaux et pour l’emménagement dans un nouveau logement.","Cleaning packages for post-construction apartments and moving into a new home."),terms:pair("Le périmètre et le prix dépendent des lieux et sont convenus avant réservation.","Scope and price depend on the space and are agreed before booking."),start:'',end:'',status:'pending'},
{id:'business',title:pair("Un soin régulier de vos espaces","Ongoing care for your space"),description:pair("Renseignez-vous sur les offres de fidélité et les tarifs dédiés aux bureaux et entreprises.","Ask about loyalty offers and special rates for offices and businesses."),terms:pair("Disponibilité, tarifs et conditions à confirmer. Il ne s’agit ni d’un abonnement en ligne ni d’un programme de points.","Availability, rates and terms require confirmation. Not an online subscription or points programme."),start:'',end:'',status:'pending'}];
export const reviews=[{id:'review-1',title:pair("Client fictif 01","Sample customer 01"),description:pair("« Exemple illustratif : un service attentif et le souci du détail. »","“Illustrative example: thoughtful service and attention to detail.”"),status:'sample'},{id:'review-2',title:pair("Client fictif 02","Sample customer 02"),description:pair("« Exemple illustratif : une coordination claire et du soin apporté aux lieux. »","“Illustrative example: clear coordination and care for our space.”"),status:'sample'}];
export const gallery=[{id:'gallery-sofa',service:'sofa',title:pair("Soin des textiles","Upholstery care"),before:photos.sofa,after:photos.sofa,status:'sample'},{id:'gallery-office',service:'office',title:pair("Des bureaux rafraîchis","Fresh workspaces"),before:photos.office,after:photos.office,status:'sample'}];
export const faqs=[
[pair("Comment obtenir un tarif ?","How do I get a price?"),pair("Précisez le service et la superficie, puis envoyez vos photos via WhatsApp. Le périmètre et le prix sont convenus avant l’intervention.","Tell us the service and size of the space, and send photos via WhatsApp. Scope and price are agreed before work starts.")],
[pair("Le choix d’un créneau confirme-t-il ma réservation ?","Does choosing a time confirm my booking?"),pair("Non. Le créneau souhaité est une demande qui doit être confirmée par l’équipe Bertrand.","No. Your preferred time is a request and needs confirmation from the Bertrand team.")],
[pair("Quelles zones desservez-vous ?","Which areas do you cover?"),pair("Bertrand Cleaning Services est basé en France. Contactez l’équipe pour confirmer la couverture de votre adresse.","Bertrand Cleaning Services is based in France. Please contact the team to confirm coverage for your address.")],
[pair("Les photos et avis sont-ils authentiques ?","Are the work photos and reviews real?"),pair("Les photos sont illustratives et les avis sont des exemples en attendant le contenu approuvé par l’entreprise.","Photos are illustrative and reviews are demo samples until approved business content is supplied.")],
[pair("Les demandes sont-elles envoyées depuis cette démonstration ?","Are requests sent from this demo?"),pair("Non. Les demandes sont simulées dans cet onglet uniquement. Rien n’est envoyé ni confirmé. Utilisez WhatsApp pour une demande réelle.","No. Requests are simulated in this tab only. Nothing is sent to the business or confirmed. Use WhatsApp for real enquiries.")]
];
