// Run with Playwright installed: node tests/browser.cjs. Optional CHROME_EXECUTABLE for an existing browser.
const {chromium}=require('playwright');const http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const errors=[];
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp','.woff2':'font/woff2'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('not found')}});
(async()=>{await new Promise(resolve=>server.listen(8081,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--in-process-gpu']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8081/';await page.goto(base);await page.locator('.hero').waitFor();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');await page.locator('#language').click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'en');
const pages=['index','services','service-home','service-sofa','service-construction','service-glass','service-deep','service-office','about','gallery','offers','contact','quote','booking','faq','privacy','terms','admin'];
for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const language of ['fr','en'])for(const file of pages){await page.goto(base+file+'.html?lang='+language);await page.locator('#main h1').waitFor();assert.equal(await page.locator('html').getAttribute('dir'),language==='fr'?'ltr':'ltr');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,`${width} ${language} ${file} overflow`);assert.ok((await page.locator('#main').innerText()).length>20);}}
console.log('PASS: 108 page/viewport/language checks');
await page.goto(base+'gallery.html?lang=en');await page.locator('.compare-slider').first().focus();await page.locator('.compare-slider').first().press('ArrowRight');assert.equal(await page.locator('.compare-slider').first().inputValue(),'51');await page.locator('#gallery-filter').selectOption('sofa');assert.equal(await page.locator('.comparison').count(),1);
await page.goto(base+'quote.html?lang=en');await page.locator('#request-form button[type=submit]').click();assert.ok((await page.locator('#error-name').innerText()).includes('complete'));await page.locator('[name=name]').fill('Browser sample');await page.locator('[name=phone]').fill('bad');await page.locator('[name=service]').selectOption('sofa');await page.locator('[name=address]').fill('Sample address');await page.locator('[name=details]').fill('Test enquiry only');await page.locator('[name=consent]').check();await page.locator('#request-form button[type=submit]').click();assert.ok((await page.locator('#error-phone').innerText()).includes('valid'));await page.locator('[name=phone]').fill('+33605597685');
await page.locator('#photos').setInputFiles({name:'invalid.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});assert.ok((await page.locator('#file-error').innerText()).includes('JPEG'));await page.locator('#photos').setInputFiles(path.join(root,'assets/s1.png'));await page.locator('.photo-preview progress[value="100"]').waitFor();await page.locator('[data-remove-photo]').click();assert.equal(await page.locator('.photo-preview').count(),0);await page.locator('#photos').setInputFiles(path.join(root,'assets/s1.png'));await page.locator('.photo-preview progress[value="100"]').waitFor();await page.locator('#request-form button[type=submit]').click();assert.ok((await page.locator('#form-alert').innerText()).includes('not sent'));await page.locator('a[href="admin.html"]').click();await page.locator('#enter-admin').click();await page.locator('[data-tab=requests]').first().click();await page.locator('#admin-search').fill('Browser sample');assert.equal(await page.locator('.admin-row').count(),1);await page.locator('[data-edit]').click();assert.equal(await page.locator('dialog .photo-previews img').count(),1);await page.locator('dialog select[name=status]').selectOption('contacted');await page.locator('#editor-form button[type=submit], #editor-form button:not([type])').click();await page.locator('#admin-status').selectOption('contacted');assert.equal(await page.locator('.admin-row').count(),1);await page.locator('#admin-status').selectOption('new');assert.equal(await page.locator('.admin-row').count(),0);
await page.locator('[data-tab=services]').click();await page.locator('[data-edit]').first().click();await page.locator('[name=title_en]').fill('Edited sample service');await page.locator('#editor-form button:not([type])').click();assert.ok((await page.locator('.admin-list').innerText()).includes('Edited sample service'));
await page.locator('[data-tab=offers]').click();await page.locator('#add-item').click();await page.locator('[name=title_fr]').fill('Offre fictive');await page.locator('[name=title_en]').fill('Sample new offer');await page.locator('[name=description_fr]').fill('Description fictive');await page.locator('[name=description_en]').fill('Sample description');await page.locator('[name=terms_fr]').fill('Conditions fictives');await page.locator('[name=terms_en]').fill('Sample terms');await page.locator('#editor-form button:not([type])').click();assert.equal(await page.locator('.admin-row').count(),4);await page.locator('[data-delete]').last().click();await page.locator('#confirm-delete').click();assert.equal(await page.locator('.admin-row').count(),3);
await page.locator('#language').click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');await page.locator('#reset-demo').click();await page.locator('[data-tab=requests]').first().click();assert.equal(await page.locator('.admin-row').count(),1);
await page.goto(base+'booking.html?lang=en');await page.locator('[name=name]').fill('Sample booking');await page.locator('[name=phone]').fill('+33605597685');await page.locator('[name=service]').selectOption('home');await page.locator('[name=address]').fill('Sample address');await page.locator('[name=date]').fill('2020-01-01');await page.locator('[name=time]').fill('10:00');await page.locator('[name=consent]').check();await page.locator('#request-form button[type=submit]').click();assert.ok((await page.locator('#error-date').innerText()).includes('future'));await page.locator('[name=date]').fill('2099-10-01');await page.locator('#request-form button[type=submit]').click();assert.ok((await page.locator('#form-alert').innerText()).includes('no booking is confirmed'));
await page.setViewportSize({width:390,height:844});await page.goto(base+'index.html?lang=fr');await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.locator('#navigation a[href="services.html"]').click();assert.ok(page.url().includes('services.html'));await page.goto(base+'index.html?lang=en');assert.equal(await page.locator('a[href="tel:+33605597685"]').count()>0,true);assert.equal(await page.locator('a[href="https://wa.me/33605597685"]').count()>0,true);
const out=process.env.SCREENSHOT_DIR;if(out){fs.mkdirSync(out,{recursive:true});await page.waitForFunction(()=>[...document.querySelectorAll('header img,.hero-image')].every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'mobile-en.png'),fullPage:false});await page.goto(base+'index.html?lang=fr');await page.waitForFunction(()=>[...document.querySelectorAll('header img,.hero-image')].every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'mobile-ar.png'),fullPage:false});await page.setViewportSize({width:1440,height:1000});await page.goto(base+'index.html?lang=en');await page.waitForFunction(()=>[...document.querySelectorAll('header img,.hero-image')].every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'desktop-en.png'),fullPage:false});await page.goto(base+'admin.html?lang=en');await page.locator('#enter-admin').click();await page.waitForFunction(()=>[...document.querySelectorAll('header img,.hero-image')].every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'admin-en.png'),fullPage:false});}
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');assert.deepEqual(errors,[]);console.log('PASS: forms, uploads, gallery, navigation, admin CRUD/filter/status/reset, contact links, reduced motion; no browser JS errors');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
