from pathlib import Path
from html import escape
import json
pages = {'index': 'Accueil', 'services': 'Services', 'about': 'À propos', 'gallery': 'Nos réalisations', 'offers': 'Offres', 'contact': 'Contact', 'quote': 'Demander un devis', 'booking': 'Demande de réservation', 'faq': 'FAQ', 'privacy': 'Politique de confidentialité', 'terms': 'Conditions générales', 'admin': 'Aperçu administrateur', 'service': 'Détails du service', 'service-home': 'Nettoyage des maisons et appartements', 'service-sofa': 'Nettoyage des canapés et tapis', 'service-construction': 'Nettoyage après travaux', 'service-glass': 'Nettoyage des vitres', 'service-deep': 'Nettoyage en profondeur', 'service-office': 'Nettoyage des bureaux'}
for page,title in pages.items():
 schema=json.dumps({"@context":"https://schema.org","@type":"LocalBusiness","name":"Bertrand Cleaning Services","telephone":"+33605597685","address":{"@type":"PostalAddress","addressCountry":"FR"}})
 Path(page+'.html').write_text(f'''<!doctype html><html lang="fr" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#123f59"><meta name="robots" content="noindex,nofollow"><title>{escape(title)} | Bertrand Cleaning Services</title><meta name="description" content="{escape(title)} — Bertrand Cleaning Services en France."><link rel="stylesheet" href="responsive-v3.css"><link rel="icon" href="assets/bertrand-wordmark.svg" type="image/svg+xml"><script type="application/ld+json">{schema}</script></head><body><div id="app"></div><noscript><h1>Bertrand Cleaning Services</h1><p>Activez JavaScript pour utiliser la démonstration.</p><a href="tel:+33605597685">+33 6 05 59 76 85</a><a href="https://wa.me/33605597685">WhatsApp</a></noscript><script type="module" src="js/app.js"></script></body></html>''')
Path('robots.txt').write_text('User-agent: *\nDisallow: /\n')
# Set approved production origin before generating canonical URLs, hreflang and sitemap.
